### ISSUE TITLE
Water does not affect player physics

### ISSUE THREAD

**Issue by bubbleawsome** [TallWorlds/CubicChunks#12]
You fall through water like air.

**Comment by kvverti** [comment]
This seems to be only below y=0.

**Comment by Razaekel** [comment]
Please confirm whether it is only below y=0, or if it occurs above y=255 as well.

**Comment by Niko-sk2x** [comment]
It also occurs above y=255.

**Comment by bubbleawsome** [comment]
Can also confirm it happens above 255. Lava is not effected at all though, above 255 or below 0.

**Comment by cuchaz** [comment]
fixed in 40840e6e851ce9d31ceaad704a0f6b9473988ab4
