### ISSUE TITLE
Some cubes aren't unloaded clientside

### ISSUE THREAD

**Issue by Niko-sk2x** [TallWorlds/CubicChunks#2]
Amount of cubes loaded clientside grows as player moves.

**Comment by AlphaFox13** [comment]
so the server is making generating chunks it main priority and ignoring the need to unload, hence bogging up the ram and causing a crash.
one solution is to limit the amount of chunks that can be loaded at any one time (based on ram available)
however that would cause problems when falling (or other fast movements)

**Comment by Niko-sk2x** [comment]
The server does unload cubes that are too far from player (just like vanilla with chunks). But for some strange reason not all of the chunks/cubes are unloaded (at least clientside, server sends cube unload packets to client).
