### ISSUE TITLE
Surface Block Replaces Air in Caves at Vertical Chunk Borders (Inconsistent)

### ISSUE THREAD

**Issue by kvverti** [TallWorlds/CubicChunks#20]
![2015-04-23_16 52 26](https://cloud.githubusercontent.com/assets/12057435/7307731/b15c77f0-e9dc-11e4-81a2-e51f17e4d568.png)
![2015-04-22_15 14 44](https://cloud.githubusercontent.com/assets/12057435/7283136/669b2700-e902-11e4-90db-8ae923ec1a30.png) This one's a gravel layer^^

**Comment by kvverti** [comment]
Not completely fixed. The gravel layer is at y=-113
![2015-06-14_17 40 15](https://cloud.githubusercontent.com/assets/12057435/8150566/89dc1b3c-12bc-11e5-94f9-087b304bf39c.png)

**Comment by Niko-sk2x** [comment]
That's weird. I will test it again. 
Are you sure that you are using the latest TWM version and that this isn't old world?

It can happen only when dirt/grass/gravel/etc is generated in cube at (x, y, z) after cave genration at (x, y+1, z). In other words, caves at (x, y, z) can be generated only if dirt/grass has been already generated in cube at (x, y-1, z). And I thought that I already fixed it.

**Comment by kvverti** [comment]
@Barteks2x Version 0.3.1b, new world. It only happens in some places, though; not everywhere like the previous version.

**Comment by Niko-sk2x** [comment]
Does it always happen with the same seed, even if you go to that place from different direction?
Or does it happen randomly, and it doesn't generate it again in the same place in new world with the same seed?
Does it generate at some specific y coordinates?

**Comment by kvverti** [comment]
It is not consistent with respect to the seed. I have only found two instances in the world, both at y=-113. I was underground in spectator mode and generating new chunks upward at the time.

**Comment by kvverti** [comment]
I think this may be a manifestation of [MC-55596](https://bugs.mojang.com/browse/MC-55596) because it is not consistent. In that case this is a vanilla bug.
