### ISSUE TITLE
World Holes / Empty Chunk Columns

### ISSUE THREAD

**Issue by kvverti** [TallWorlds/CubicChunks#22]
Chunk column errors are common when exploring new chunks while flying in creative. Sometimes a group of chunks don't generate, but more common are chunk columns that are empty, but lit, as if they were flagged as generated. This doesn't seem to be the same as a normal chunk error, because it is lit and occurs in columns.
![2015-04-22_17 44 16](https://cloud.githubusercontent.com/assets/12057435/7307576/b54b49d2-e9db-11e4-8106-7730ff06de2f.png) vvThese chunk column won't generate any of its chunks^^
![2015-04-23_16 48 36](https://cloud.githubusercontent.com/assets/12057435/7307577/b54caf20-e9db-11e4-9196-dacde00f0a84.png)
![2015-04-23_16 59 36](https://cloud.githubusercontent.com/assets/12057435/7307578/b550b8cc-e9db-11e4-984f-c92566a9af67.png)
![2015-04-23_16 55 13](https://cloud.githubusercontent.com/assets/12057435/7307575/b546ae4a-e9db-11e4-8187-3f93ea4cafae.png) A "vanilla" chunk error for comparison^^

**Comment by Niko-sk2x** [comment]
It looks like some cubes are sent before columns (with biome and lighting data):
"ERROR Client thread tallworlds: Ignored 4/81 cubes that arrived before their columns"
