### ISSUE TITLE
[Suggestion] API for forge to hook into as secondary modloder for M3L(may be a WIP already)

### ISSUE THREAD

**Issue by Prophious** [TallWorlds/CubicChunks#31]
sorry could not find the right github for the M3L so i'm posting here (close or move if necessary)

as many ppl will not go to a new modloder API to code to, i suggest that M3L gets a forge API hook to run the forge mods side-by-side

i dont know if this is the intention of the new modloader or not, but as more and more mods are added to minecraft 1.8.3+ compatibility they should be able to run with this modloader out the gate

if needed you could see if the forge coders are willing to create a hook for M3L so then M3L will only run mods that --it-- needs to run

honestly i would like to see this working(M3L with Tall Worlds along with other forge mods)

**Comment by Niko-sk2x** [comment]
M3L is on bitbucket [here](https://bitbucket.org/cuchaz/m3l).
