### ISSUE TITLE
List of glitches and issues ( mainly in y<0)

### ISSUE THREAD

**Issue by pedroff1** [TallWorlds/CubicChunks#34]
1-Commands that involve y coordinate don't work on y<0 or y>255, /spawnpoint works (as long as without the coords)
2-After respawning  or even at will, items despawn or turn invisible in y<0 chunks
3-after some respawning, blocks placement in y<0 just deletes the block at wich your pointr is at, instead of placing a block (solved by relogging)
4-broken lightning in y<0
5- as noticed by some and confirmed, liquids don't update/update very  slowly in y<0(they update when you relog)
6- anything more complex than a redstone torch (repeaters-comparators to pistons) doesn't work in y<0
7-Night vision makes you 100% blind (as much or more than blidness+night vision in vanilla) in y<0
8- saddleless horses spin like crazy(they stop as you put the saddle, but as you take, any damage thay take make them return to spinning)
Tested at y=-3782
9- really weird generation glitches over y=-4000 (giant fake chunk corridor)
10- lightning madness after said limit

**Comment by mikesmiffy128** [comment]
Good job finding all this but you're not supposed to cram 10 reports into a single issue. Now 9 of these could be fixed and the developers would have to keep it open, so at first glance it would be hard to figure out which thing still needs fixed, which may lead to issues taking longer to fix.

Just a thought.

**Comment by Razaekel** [comment]
1 - #15 
2 - #36 - Provide more details.
3 - #37
4 - Is this similar to #21 ? If so, add more examples to that issue.
5 - #10 
6 - #38
7 - #13 
8 - #39
9 - Examples? create a new issue with details and pictures.
10 - Examples? create a new issue with details and pictures.

Next time, please create separate issue reports and provide more details or pictures.

**Comment by cuchaz** [comment]
Thanks for taking the time to separate those. =)

**Comment by pedroff1** [comment]
thank you all for replying me and making things clearer, next time I'll try to make separate reports, also, should I make reports for the ones without or they already count being in here?

**Comment by mikesmiffy128** [comment]
Wha.. what?

**Comment by pedroff1** [comment]
I meant to ask wheter I should do another report for the glitches without other reports, so they would have an individual report each or not.

**Comment by mikesmiffy128** [comment]
**Every** unrelated issue should be its own report. 8 of them are already linked above, because Razaekel is kind and helpful. You should report the other two with more information as already explained above.
