### ISSUE TITLE
Text doubling

### ISSUE THREAD

**Issue by AnonymousUser52** [TallWorlds/CubicChunks#44]
For example: the difficulty button, "DifficultyDifficulty: NormalNormal", and error messages in chat do it too.

**Comment by mikesmiffy128** [comment]
M3L issue. Already opened for M3L, already opened and closed over here. Please close this.

**Comment by AnonymousUser52** [comment]
Ok,

**Comment by mikesmiffy128** [comment]
Wow this issue was open literally 2 and a half minutes. Is this like the shortest-lived issue ever? :P

**Comment by AnonymousUser52** [comment]
Probably. Where is the M3L thing?

**Comment by mikesmiffy128** [comment]
[Here.](https://bitbucket.org/cuchaz/m3l/issues/8/double-text-bug)

**Comment by AnonymousUser52** [comment]
thanks.
