### ISSUE TITLE
Text is repeated twice

### ISSUE THREAD

**Issue by jumpsplat120** [TallWorlds/CubicChunks#45]
Certain bits of text are printed twice. "DifficultyDifficulty:NormalNormal" and "jumpsplat120 has earned the Achievement [AchievementNameAcheivementName]jumpsplat120 has earned the Achievement [AchievementNameAcheivementName]"

**Comment by Razaekel** [comment]
M3L issue, not Tall Worlds.

https://bitbucket.org/cuchaz/m3l/issues/8/double-text-bug

**Comment by mikesmiffy128** [comment]
This is like the third time this issue was opened here. Is it worth mentioning it somewhere in the README or something so people don't keep re-reporting it?
